 CREATE TABLE USUARIO 
   (ID_USUARIO NUMBER(4,0) NOT NULL PRIMARY KEY, 
	USUARIO VARCHAR2(20 BYTE) NOT NULL , 
	CLAVE VARCHAR2(80 BYTE) NOT NULL , 
	NOMBRE VARCHAR2(120 BYTE)NOT NULL
    );
    
CREATE TABLE ALBUM
   (    CODIGO NUMBER(4,0) NOT NULL  PRIMARY KEY, 
        NOMBRE VARCHAR2(280 BYTE) NOT NULL , 
        DESCRIPCION VARCHAR2(4000 BYTE), 
    	ESTADO CHAR(1 BYTE) DEFAULT 1 NOT NULL
);   