INSERT INTO USUARIO(ID_USUARIO,USUARIO,CLAVE,NOMBRE)
VALUES(SEQ_USUARIO.NEXTVAL,'ADMIN','$2a$10$RjPpZ6UvfkDBhaqGKClAh.FR3VvouSYU33FgG5usCoklvgFaQdGfW','ADMINISTRADOR');
COMMIT;

SELECT ID_USUARIO,USUARIO,CLAVE,NOMBRE FROM USUARIO;

INSERT INTO ALBUM(CODIGO,NOMBRE,DESCRIPCION)
VALUES(SEQ_ALBUM.NEXTVAL,'Fotos familiares','Cumpleaños de la abuela');
INSERT INTO ALBUM(CODIGO,NOMBRE,DESCRIPCION)
VALUES(SEQ_ALBUM.NEXTVAL,'Viaje a cusco','Primer viaje a cusco');
INSERT INTO ALBUM(CODIGO,NOMBRE,DESCRIPCION)
VALUES(SEQ_ALBUM.NEXTVAL,'Fotos de Capacitacion en Java','Java, Spring Boot, Docker y Kubernate');

COMMIT;

SELECT CODIGO,NOMBRE,DESCRIPCION FROM ALBUM;
